baseURL = 'https://www.les.cx/'
languageCode = 'en-us'
defaultcontentlanguage = 'en'
timezone = 'Europe/Berlin'
title = 'Luca Etienne Schulz'
disablehugogeneratorinject = true
cleanDestinationDir = true
theme = 'asciigram'
