baseURL = 'https://www.les.cx/'
languageCode = 'en-us'
defaultcontentlanguage = 'en'
timezone = 'Europe/Berlin'
title = 'Luca Etienne Schulz'
disablehugogeneratorinject = true
cleanDestinationDir = true
theme = 'asciigram'

disableKinds = ['taxonomy']

[module]
  [module.hugoVersion]
    extended = false
    min = "0.121.1"

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.atom]
    mediaType = "application/atom+xml"
    baseName  = "index"

[outputs]
  home = ['html']
  section = ['html', 'atom']