[params.author]
name = 'Luca Etienne Schulz'
email = 'luca@les.cx'
github = 'https://github.com/lescx'
codeberg = 'https://codeberg.org/les'
nostr = 'npub1wnwxt4hg3xg6egc4v8r5zjclf0v2745yq50t5uzhx794h2z8gwwqszpm3w'